"""add_user_broker_credentials

Revision ID: 0452399fa014
Revises: 87def8a71309
Create Date: 2026-07-04 12:31:43.799909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0452399fa014'
down_revision: Union[str, None] = '87def8a71309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_broker_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('api_secret_enc', sa.Text(), nullable=False),
    sa.Column('extras_enc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'broker', name='uq_user_broker')
    )
    op.create_index(op.f('ix_user_broker_credentials_broker'), 'user_broker_credentials', ['broker'], unique=False)
    op.create_index(op.f('ix_user_broker_credentials_username'), 'user_broker_credentials', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_broker_credentials_username'), table_name='user_broker_credentials')
    op.drop_index(op.f('ix_user_broker_credentials_broker'), table_name='user_broker_credentials')
    op.drop_table('user_broker_credentials')
    # ### end Alembic commands ###
