"""add_parent_child_symbols

Revision ID: 6288abd1a363
Revises: 0452399fa014
Create Date: 2026-07-05 12:04:56.331922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6288abd1a363'
down_revision: Union[str, None] = '0452399fa014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('instrumenttype', sa.String(), nullable=True),
    sa.Column('expiry', sa.String(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('lotsize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_symbol_identity')
    )
    op.create_index(op.f('ix_symbols_exchange'), 'symbols', ['exchange'], unique=False)
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=False)
    op.create_table('broker_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('brsymbol', sa.String(), nullable=False),
    sa.Column('brexchange', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'brexchange', 'token', name='uq_broker_token'),
    sa.UniqueConstraint('broker', 'brsymbol', 'brexchange', name='uq_broker_brsymbol')
    )
    op.create_index(op.f('ix_broker_symbols_brexchange'), 'broker_symbols', ['brexchange'], unique=False)
    op.create_index(op.f('ix_broker_symbols_broker'), 'broker_symbols', ['broker'], unique=False)
    op.create_index(op.f('ix_broker_symbols_brsymbol'), 'broker_symbols', ['brsymbol'], unique=False)
    op.create_index(op.f('ix_broker_symbols_symbol_id'), 'broker_symbols', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_broker_symbols_token'), 'broker_symbols', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_symbols_token'), table_name='broker_symbols')
    op.drop_index(op.f('ix_broker_symbols_symbol_id'), table_name='broker_symbols')
    op.drop_index(op.f('ix_broker_symbols_brsymbol'), table_name='broker_symbols')
    op.drop_index(op.f('ix_broker_symbols_broker'), table_name='broker_symbols')
    op.drop_index(op.f('ix_broker_symbols_brexchange'), table_name='broker_symbols')
    op.drop_table('broker_symbols')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_exchange'), table_name='symbols')
    op.drop_table('symbols')
    # ### end Alembic commands ###
