"""add_user_status_role

Revision ID: 87def8a71309
Revises: adfecdc9adde
Create Date: 2026-07-01 11:05:07.477214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87def8a71309'
down_revision: Union[str, None] = 'adfecdc9adde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
