"""baseline_existing_schema

Revision ID: adfecdc9adde
Revises: 
Create Date: 2026-06-30 14:50:27.487377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfecdc9adde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=True),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_active_sessions_username', 'active_sessions', ['username'], unique=False)
    op.create_index(op.f('ix_active_sessions_username'), 'active_sessions', ['username'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_mode', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_api_keys_created_at', 'api_keys', ['created_at'], unique=False)
    op.create_index('idx_api_keys_order_mode', 'api_keys', ['order_mode'], unique=False)
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('feed_token', sa.Text(), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('secret_api_key', sa.Text(), nullable=True),
    sa.Column('primary_ip', sa.String(length=45), nullable=True),
    sa.Column('secondary_ip', sa.String(length=45), nullable=True),
    sa.Column('ip_updated_at', sa.DateTime(), nullable=True),
    sa.Column('aux_param1', sa.Text(), nullable=True),
    sa.Column('aux_param2', sa.Text(), nullable=True),
    sa.Column('aux_param3', sa.Text(), nullable=True),
    sa.Column('aux_param4', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_auth_broker', 'auth', ['broker'], unique=False)
    op.create_index('idx_auth_is_revoked', 'auth', ['is_revoked'], unique=False)
    op.create_index('idx_auth_user_id', 'auth', ['user_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('login_type', sa.String(length=20), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_attempts_status', 'login_attempts', ['status'], unique=False)
    op.create_index('idx_login_attempts_timestamp', 'login_attempts', ['timestamp'], unique=False)
    op.create_index('idx_login_attempts_username', 'login_attempts', ['username'], unique=False)
    op.create_table('symtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('brsymbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('brexchange', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expiry', sa.String(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('lotsize', sa.Integer(), nullable=True),
    sa.Column('instrumenttype', sa.String(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brsymbol_exchange', 'symtoken', ['brsymbol', 'exchange'], unique=False)
    op.create_index('idx_symbol_exchange', 'symtoken', ['symbol', 'exchange'], unique=False)
    op.create_index('idx_symbol_name', 'symtoken', ['symbol', 'name'], unique=False)
    op.create_index(op.f('ix_symtoken_brexchange'), 'symtoken', ['brexchange'], unique=False)
    op.create_index(op.f('ix_symtoken_brsymbol'), 'symtoken', ['brsymbol'], unique=False)
    op.create_index(op.f('ix_symtoken_exchange'), 'symtoken', ['exchange'], unique=False)
    op.create_index(op.f('ix_symtoken_symbol'), 'symtoken', ['symbol'], unique=False)
    op.create_index(op.f('ix_symtoken_token'), 'symtoken', ['token'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_required_for_login', sa.Boolean(), nullable=False),
    sa.Column('totp_required_for_mcp', sa.Boolean(), nullable=False),
    sa.Column('totp_required_for_password_reset', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_symtoken_token'), table_name='symtoken')
    op.drop_index(op.f('ix_symtoken_symbol'), table_name='symtoken')
    op.drop_index(op.f('ix_symtoken_exchange'), table_name='symtoken')
    op.drop_index(op.f('ix_symtoken_brsymbol'), table_name='symtoken')
    op.drop_index(op.f('ix_symtoken_brexchange'), table_name='symtoken')
    op.drop_index('idx_symbol_name', table_name='symtoken')
    op.drop_index('idx_symbol_exchange', table_name='symtoken')
    op.drop_index('idx_brsymbol_exchange', table_name='symtoken')
    op.drop_table('symtoken')
    op.drop_index('idx_login_attempts_username', table_name='login_attempts')
    op.drop_index('idx_login_attempts_timestamp', table_name='login_attempts')
    op.drop_index('idx_login_attempts_status', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index('idx_auth_user_id', table_name='auth')
    op.drop_index('idx_auth_is_revoked', table_name='auth')
    op.drop_index('idx_auth_broker', table_name='auth')
    op.drop_table('auth')
    op.drop_index('idx_api_keys_order_mode', table_name='api_keys')
    op.drop_index('idx_api_keys_created_at', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_active_sessions_username'), table_name='active_sessions')
    op.drop_index('idx_active_sessions_username', table_name='active_sessions')
    op.drop_table('active_sessions')
    # ### end Alembic commands ###
